<a href="https://colab.research.google.com/github/ritikavijayy/mlReva/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import random 
number=random.random()
print(number)

0.10349077658729189


In [3]:
import random 
number=random.randint(1,10)


print(number)


10


import numpy 


In [4]:
import numpy as np 


In [5]:
a=np.array([0,1,2,3])

In [6]:
b=np.array([1,3,4,6])
b

array([1, 3, 4, 6])

In [7]:
a*b

array([ 0,  3,  8, 18])

In [8]:
c=np.array([[0,1,2,3],[10,11,12,13]])
c

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [9]:
c.shape

(2, 4)

In [10]:
c[1,3]=-1
c

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [11]:
a[1:3] #slicing 

array([1, 2])

In [12]:
a[-1:3]
a

array([0, 1, 2, 3])

In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
newarr=arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
c=np.arange(216).reshape(6,6,6) #generate numbers till 24-arange
c

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35]],

       [[ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107]],

       [[108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130, 131],
        [132, 133, 134, 135, 136, 137],
        [138, 139, 140, 141, 142, 143]],

       [[144, 145, 146, 147, 148

In [16]:
c=np.arange(0,125,5).reshape(5,5)
c

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120]])

In [17]:
c[0,3:5]
c

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120]])

In [18]:
c[2][:2]
c[3,:]
c[:,2].reshape(5,1)

array([[ 10],
       [ 35],
       [ 60],
       [ 85],
       [110]])

In [19]:
c[2,2:3]
c

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120]])

In [20]:
c[2,:]

array([50, 55, 60, 65, 70])

In [21]:
c[:,2]#.reshape(5,1)

array([ 10,  35,  60,  85, 110])

In [22]:
c

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120]])

In [26]:
d=np.arange(-15,15).reshape(5,6)**6
d

array([[11390625,  7529536,  4826809,  2985984,  1771561,  1000000],
       [  531441,   262144,   117649,    46656,    15625,     4096],
       [     729,       64,        1,        0,        1,       64],
       [     729,     4096,    15625,    46656,   117649,   262144],
       [  531441,  1000000,  1771561,  2985984,  4826809,  7529536]])

In [24]:
import numpy as np 

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
arr = np.loadtxt('data.txt',dtype= int,skiprows= 2,delimiter=',',comments='#')

In [32]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99],
       [101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [35]:
arr.sum()

1485

In [40]:
arr.sum(axis=0) # axis '0' refers to x-axis , axis 1 refers to y-axis

array([113, 126, 139, 152, 165, 178, 191, 204, 217])

In [39]:
arr.sum(axis=1)

array([ 45, 495, 945])

In [41]:
arr.min()

1

In [42]:
arr.max()

109

In [43]:
arr.std()

44.04543109109048

In [45]:
arr.mean()


55.0

In [46]:
arr.var()

1940.0

In [47]:
import pandas

In [48]:
help(pandas)

Help on package pandas:

NAME
    pandas

DESCRIPTION
    pandas - a powerful data analysis and manipulation library for Python
    
    **pandas** is a Python package providing fast, flexible, and expressive data
    structures designed to make working with "relational" or "labeled" data both
    easy and intuitive. It aims to be the fundamental high-level building block for
    doing practical, **real world** data analysis in Python. Additionally, it has
    the broader goal of becoming **the most powerful and flexible open source data
    analysis / manipulation tool available in any language**. It is already well on
    its way toward this goal.
    
    Main Features
    -------------
    Here are just a few of the things that pandas does well:
    
      - Easy handling of missing data in floating point as well as non-floating
        point data.
      - Size mutability: columns can be inserted and deleted from DataFrame and
        higher dimensional objects
      - Automatic an

In [49]:
import pandas as pd


In [53]:
pandas.DataFrame(arr)

0    1    2    3    4    5    6    7    8
0    1    2    3    4    5    6    7    8    9
1   11   22   33   44   55   66   77   88   99
2  101  102  103  104  105  106  107  108  109

In [54]:
df=pd.read_csv('prime.csv')

In [55]:
df

2        3        5          7         11         13         17   \
0           31       37       41       43.0       47.0       53.0       59.0   
1           73       79       83       89.0       97.0      101.0      103.0   
2          127      131      137      139.0      149.0      151.0      157.0   
3          179      181      191      193.0      197.0      199.0      211.0   
4          233      239      241      251.0      257.0      263.0      269.0   
...        ...      ...      ...        ...        ...        ...        ...   
41993  6110509  6110519  6110521  6110527.0  6110549.0  6110551.0  6110563.0   
41994  6110593  6110623  6110683  6110711.0  6110717.0  6110719.0  6110747.0   
41995  6110827  6110831  6110843  6110861.0  6110933.0  6110941.0  6110969.0   
41996  6110983  6111011  6111013  6111023.0  6111029.0  6111047.0  6111071.0   
41997  6111151  6111167     6111        NaN        NaN        NaN        NaN   

             19         23         29        
0           61.0       67.0       71.0       
1          107.0      109.0      113.0       
2          163.0      167.0      173.0       
3          223.0      227.0      229.0       
4          271.0      277.0      281.0       
...          ...        ...        ...  ...  
41993  6110567.0  6110569.0  6110581.0       
41994  6110749.0  6110777.0  6110789.0       
41995  6110971.0  6110977.0  6110981.0       
41996  6111073.0  6111089.0  6111139.0       
41997        NaN        NaN        NaN  NaN  

[41998 rows x 11 columns]

In [57]:
df=pd.read_csv('prime.csv',header=None)

In [58]:
df.index

RangeIndex(start=0, stop=41999, step=1)

In [61]:
df.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [62]:
df.shape

(41999, 11)

In [63]:
df.axes

[RangeIndex(start=0, stop=41999, step=1),
 Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')]

In [64]:
df.empty

False

In [65]:
df.ndim

2

In [67]:
df.dtypes

0       int64
1       int64
2       int64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10     object
dtype: object

In [70]:
df.size

461989

In [75]:
df.loc[0:10]

0    1    2      3      4      5      6      7      8      9   10
0     2    3    5    7.0   11.0   13.0   17.0   19.0   23.0   29.0    
1    31   37   41   43.0   47.0   53.0   59.0   61.0   67.0   71.0    
2    73   79   83   89.0   97.0  101.0  103.0  107.0  109.0  113.0    
3   127  131  137  139.0  149.0  151.0  157.0  163.0  167.0  173.0    
4   179  181  191  193.0  197.0  199.0  211.0  223.0  227.0  229.0    
5   233  239  241  251.0  257.0  263.0  269.0  271.0  277.0  281.0    
6   283  293  307  311.0  313.0  317.0  331.0  337.0  347.0  349.0    
7   353  359  367  373.0  379.0  383.0  389.0  397.0  401.0  409.0    
8   419  421  431  433.0  439.0  443.0  449.0  457.0  461.0  463.0    
9   467  479  487  491.0  499.0  503.0  509.0  521.0  523.0  541.0    
10  547  557  563  569.0  571.0  577.0  587.0  593.0  599.0  601.0

In [79]:
df.loc[1,[2,5]]

2      41
5    53.0
Name: 1, dtype: object

In [80]:
df.loc[:,1]

0              3
1             37
2             79
3            131
4            181
          ...   
41994    6110519
41995    6110623
41996    6110831
41997    6111011
41998    6111167
Name: 1, Length: 41999, dtype: int64

In [82]:
df.iloc[-1,:]

0     6111151
1     6111167
2        6111
3         NaN
4         NaN
5         NaN
6         NaN
7         NaN
8         NaN
9         NaN
10        NaN
Name: 41998, dtype: object

In [84]:
df.iloc[0:100,0:]

0     1     2       3       4       5       6       7       8       9   \
0      2     3     5     7.0    11.0    13.0    17.0    19.0    23.0    29.0   
1     31    37    41    43.0    47.0    53.0    59.0    61.0    67.0    71.0   
2     73    79    83    89.0    97.0   101.0   103.0   107.0   109.0   113.0   
3    127   131   137   139.0   149.0   151.0   157.0   163.0   167.0   173.0   
4    179   181   191   193.0   197.0   199.0   211.0   223.0   227.0   229.0   
..   ...   ...   ...     ...     ...     ...     ...     ...     ...     ...   
95  7507  7517  7523  7529.0  7537.0  7541.0  7547.0  7549.0  7559.0  7561.0   
96  7573  7577  7583  7589.0  7591.0  7603.0  7607.0  7621.0  7639.0  7643.0   
97  7649  7669  7673  7681.0  7687.0  7691.0  7699.0  7703.0  7717.0  7723.0   
98  7727  7741  7753  7757.0  7759.0  7789.0  7793.0  7817.0  7823.0  7829.0   
99  7841  7853  7867  7873.0  7877.0  7879.0  7883.0  7901.0  7907.0  7919.0   

    10  
0       
1       
2       
3       
4       
..  ..  
95      
96      
97      
98      
99      

[100 rows x 11 columns]

In [85]:
del df[0]

In [86]:
df

1        2          3          4          5          6   \
0            3        5        7.0       11.0       13.0       17.0   
1           37       41       43.0       47.0       53.0       59.0   
2           79       83       89.0       97.0      101.0      103.0   
3          131      137      139.0      149.0      151.0      157.0   
4          181      191      193.0      197.0      199.0      211.0   
...        ...      ...        ...        ...        ...        ...   
41994  6110519  6110521  6110527.0  6110549.0  6110551.0  6110563.0   
41995  6110623  6110683  6110711.0  6110717.0  6110719.0  6110747.0   
41996  6110831  6110843  6110861.0  6110933.0  6110941.0  6110969.0   
41997  6111011  6111013  6111023.0  6111029.0  6111047.0  6111071.0   
41998  6111167     6111        NaN        NaN        NaN        NaN   

              7          8          9    10  
0           19.0       23.0       29.0       
1           61.0       67.0       71.0       
2          107.0      109.0      113.0       
3          163.0      167.0      173.0       
4          223.0      227.0      229.0       
...          ...        ...        ...  ...  
41994  6110567.0  6110569.0  6110581.0       
41995  6110749.0  6110777.0  6110789.0       
41996  6110971.0  6110977.0  6110981.0       
41997  6111073.0  6111089.0  6111139.0       
41998        NaN        NaN        NaN  NaN  

[41999 rows x 10 columns]