<a href="https://colab.research.google.com/github/ritikavijayy/mlReva/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import random 
number=random.random()
print(number)

0.23047296643239001


In [4]:
import random 
number=random.randint(1,10)


print(number)


2


import numpy 


In [5]:
import numpy as np 


In [6]:
a=np.array([0,1,2,3])

In [7]:
b=np.array([1,3,4,6])
b

array([1, 3, 4, 6])

In [8]:
a*b

array([ 0,  3,  8, 18])

In [9]:
c=np.array([[0,1,2,3],[10,11,12,13]])
c

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [10]:
c.shape

(2, 4)

In [11]:
c[1,3]=-1
c

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [12]:
a[1:3] #slicing 

array([1, 2])

In [13]:
a[2:3]
a

array([0, 1, 2, 3])