<a href="https://colab.research.google.com/github/ritikavijayy/mlReva/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random 
number=random.random()
print(number)

0.9441188417498745


In [2]:
import random 
number=random.randint(1,10)


print(number)


8


import numpy 


In [3]:
import numpy as np 


In [4]:
a=np.array([0,1,2,3])

In [5]:
b=np.array([1,3,4,6])
b

array([1, 3, 4, 6])

In [6]:
a*b

array([ 0,  3,  8, 18])

In [7]:
c=np.array([[0,1,2,3],[10,11,12,13]])
c

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [8]:
c.shape

(2, 4)

In [9]:
c[1,3]=-1
c

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [10]:
a[1:3] #slicing 

array([1, 2])

In [11]:
a[-1:3]
a

array([0, 1, 2, 3])

In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
newarr=arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
c=np.arange(216).reshape(6,6,6) #generate numbers till 24-arange
c

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35]],

       [[ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107]],

       [[108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130, 131],
        [132, 133, 134, 135, 136, 137],
        [138, 139, 140, 141, 142, 143]],

       [[144, 145, 146, 147, 148

In [15]:
c=np.arange(0,125,5).reshape(5,5)
c

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120]])

In [16]:
c[0,3:5]
c

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120]])

In [17]:
c[2][:2]
c[3,:]
c[:,2].reshape(5,1)

array([[ 10],
       [ 35],
       [ 60],
       [ 85],
       [110]])

In [18]:
c[2,2:3]
c

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120]])

In [19]:
c[2,:]

array([50, 55, 60, 65, 70])

In [20]:
c[:,2]#.reshape(5,1)

array([ 10,  35,  60,  85, 110])

In [21]:
c

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120]])

In [22]:
d=np.arange(-15,15).reshape(5,6)**6
d

array([[11390625,  7529536,  4826809,  2985984,  1771561,  1000000],
       [  531441,   262144,   117649,    46656,    15625,     4096],
       [     729,       64,        1,        0,        1,       64],
       [     729,     4096,    15625,    46656,   117649,   262144],
       [  531441,  1000000,  1771561,  2985984,  4826809,  7529536]])

In [23]:
import numpy as np 

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])